---
title: "IRR Stats"
author: "Mikey Saugstad"
date: "March 30, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(tidyr)
library(dplyr)
library(ggplot2)

my.theme.discrete.x <- theme_bw() + theme(panel.grid.major.x = element_blank())

# Run the following in console when you want to generate github flavored markdown as well.
# library(rmarkdown)
# render('R/irr_stats.Rmd', c('html_document', 'github_document'))
```


```{r reading.cleaning, echo=FALSE}
agreement.classes <- c('numeric', 'factor', 'factor', 'factor', 'numeric', 'numeric')
agreement.data <- read.csv('../data/irr_results-not_for_humans.csv', colClasses = agreement.classes)
# attach(agreement.data)

label.type.levels.in.order <- c('CurbRamp','NoCurbRamp','Obstacle','SurfaceProb','Problem')
clean.agreement.data <-
  agreement.data %>%
  mutate(label.type = case_when(
            data.type %in% c('prob.binary', 'prob.ordinal') ~ 'Problem',
            label.type == 'SurfaceProblem'                  ~ 'SurfaceProb',
            TRUE                                            ~ as.character(label.type)
          ),
         data.type = if_else(data.type %in% c('prob.binary', 'binary'),
                             'binary',
                             'ordinal')) %>%
  filter(level != '10m',
         label.type %in% c('CurbRamp', 'NoCurbRamp', 'Obstacle', 'SurfaceProb', 'Problem')) %>%
  mutate(data.type = factor(data.type),
         level = factor(level),
         label.type = factor(label.type, label.type.levels.in.order))
```

Graphs are at the bottom, but here are the IRR numbers in tables...

Ordinal, street-level, kripp alpha:

```{r table.ordinal.street.kripp, echo=FALSE}
kable(
  clean.agreement.data %>%
    filter(data.type == 'ordinal', level == 'street') %>%
    select(round.code, label.type, kripp.alpha) %>%
    spread(round.code, kripp.alpha),
  align = 'l'
)
```

Ordinal, street-level, agreement:

```{r table.ordinal.street.agreement, echo=FALSE}
kable(
  clean.agreement.data %>%
    filter(data.type == 'ordinal', level == 'street') %>%
    select(round.code, label.type, agreement) %>%
    spread(round.code, agreement),
  align = 'l'
)
```

Ordinal, 5m-level, kripp alpha:

```{r table.ordinal.5m.kripp, echo=FALSE}
kable(
  clean.agreement.data %>%
    filter(data.type == 'ordinal', level == '5m') %>%
    select(round.code, label.type, kripp.alpha) %>%
    spread(round.code, kripp.alpha),
  align = 'l'
)
```

Ordinal, 5m-level, agreement:

```{r table.ordinal.5m.agreement, echo=FALSE}
kable(
  clean.agreement.data %>%
    filter(data.type == 'ordinal', level == '5m') %>%
    select(round.code, label.type, agreement) %>%
    spread(round.code, agreement),
  align = 'l'
)
```

Binary, street-level, kripp alpha:

```{r table.binary.street.kripp, echo=FALSE}
kable(
  clean.agreement.data %>%
    filter(data.type == 'binary', level == 'street') %>%
    select(round.code, label.type, kripp.alpha) %>%
    spread(round.code, kripp.alpha),
  align = 'l'
)
```

Binary, street-level, agreement:

```{r table.binary.street.agreement, echo=FALSE}
kable(
  clean.agreement.data %>%
    filter(data.type == 'binary', level == 'street') %>%
    select(round.code, label.type, agreement) %>%
    spread(round.code, agreement),
  align = 'l'
)
```

Binary, 5m-level, kripp alpha:

```{r table.binary.5m.kripp, echo=FALSE}
kable(
  clean.agreement.data %>%
    filter(data.type == 'binary', level == '5m') %>%
    select(round.code, label.type, kripp.alpha) %>%
    spread(round.code, kripp.alpha),
  align = 'l'
)
```

Binary, 5m-level, agreement:

```{r table.binary.5m.agreement, echo=FALSE}
kable(
  clean.agreement.data %>%
    filter(data.type == 'binary', level == '5m') %>%
    select(round.code, label.type, agreement) %>%
    spread(round.code, agreement),
  align = 'l'
)
```

And now for the plots!

```{r lattice.plots, echo=FALSE, fig.height=6, fig.width=8}
ggplot(data = clean.agreement.data, aes(x = round.code, y = kripp.alpha)) +
  geom_line(aes(color = level)) +
  scale_x_continuous(breaks = 1:7) +
  scale_y_continuous(limits = c(0, 1), expand = c(0.02, 0)) +
  facet_grid(label.type ~ data.type) +
  my.theme.discrete.x +
  ggtitle('Krippendorff\'s Alpha Across Rounds') +
  xlab('Round') +
  ylab('Krippendorff\'s Alpha')

ggplot(data = clean.agreement.data, aes(x = round.code, y = agreement)) +
  geom_line(aes(color = level)) +
  scale_x_continuous(breaks = 1:7) +
  scale_y_continuous(limits = c(0, 100), expand = c(0.02, 0)) +
  facet_grid(label.type ~ data.type) +
  my.theme.discrete.x +
  ggtitle('Percentage Agreement Across Rounds') +
  xlab('Round') +
  ylab('Percentage Agreement')
```
